export const ASSET_BASE = "/assets/office";

export const OFFICE_ASSETS = {
  "amethyst": "amethyst.png",
  "anvil": "anvil.png",
  "aquarium_sofa": "aquarium_sofa.png",
  "armchair_green": "armchair_green.png",
  "barrel": "barrel.png",
  "battery": "battery.png",
  "battery2": "battery2.png",
  "battery3": "battery3.png",
  "bed1": "bed1.png",
  "bibliotheque": "bibliotheque.png",
  "biohazard_box": "biohazard_box.png",
  "black_flag": "black_flag.png",
  "black_medieval_chair": "black_medieval_chair.png",
  "blue_medieval_chair": "blue_medieval_chair.png",
  "bonxing_bag3": "bonxing_bag3.png",
  "bookcase_brown": "bookcase_brown.png",
  "bookcase_small": "bookcase_small.png",
  "bookshelf1": "bookshelf1.png",
  "bookshelf2": "bookshelf2.png",
  "bookshelf4": "bookshelf4.png",
  "bookshelf5": "bookshelf5.png",
  "bookshelf6": "bookshelf6.png",
  "bookshelf_3": "bookshelf_3.png",
  "bookshelf_lounge": "bookshelf_lounge.png",
  "boxing_bag": "boxing_bag.png",
  "boxing_bag2": "boxing_bag2.png",
  "bureau": "bureau.png",
  "cabine_douche": "cabine_douche.png",
  "cabinet_big": "cabinet_big.png",
  "cards": "cards.png",
  "chair_blue": "chair_blue.png",
  "chair_red": "chair_red.png",
  "chair_wood": "chair_wood.png",
  "chemistry_bottle": "chemistry_bottle.png",
  "chemistry_flasks": "chemistry_flasks.png",
  "chest_of_drawers": "chest_of_drawers.png",
  "coffee_machine": "coffee_machine.png",
  "coffee_table": "coffee_table.png",
  "commode": "commode.png",
  "commode_arriere": "commode_arriere.png",
  "commode_face": "commode_face.png",
  "conference_table": "conference_table.png",
  "cooker_hood": "cooker_hood.png",
  "cooking_hood2": "cooking_hood2.png",
  "cooking_robot": "cooking_robot.png",
  "couch_red_small": "couch_red_small.png",
  "cozy_sofa": "cozy_sofa.png",
  "dark_pruple_sofa": "dark_pruple_sofa.png",
  "death_totem": "death_totem.png",
  "desk_simple": "desk_simple.png",
  "diy_table": "diy_table.png",
  "diy_table2": "diy_table2.png",
  "dracula_chair": "dracula_chair.png",
  "dresser_brown": "dresser_brown.png",
  "fauteuil_rouge": "fauteuil_rouge.png",
  "fenetre": "fenetre.png",
  "fighting_dummy2": "fighting_dummy2.png",
  "fighting_dummy3": "fighting_dummy3.png",
  "fighting_dummy4": "fighting_dummy4.png",
  "fireplace": "fireplace.png",
  "flag_holder": "flag_holder.png",
  "floor_acacia_planks": "floor_acacia_planks.png",
  "floor_bamboo_planks": "floor_bamboo_planks.png",
  "floor_birch_planks": "floor_birch_planks.png",
  "floor_blue": "floor_blue.png",
  "floor_bricks": "floor_bricks.png",
  "floor_checker": "floor_checker.png",
  "floor_cherry_planks": "floor_cherry_planks.png",
  "floor_cobblestone": "floor_cobblestone.png",
  "floor_dark_oak_planks": "floor_dark_oak_planks.png",
  "floor_deepslate_bricks": "floor_deepslate_bricks.png",
  "floor_deepslate_tiles": "floor_deepslate_tiles.png",
  "floor_glass": "floor_glass.png",
  "floor_green_stained_glass": "floor_green_stained_glass.png",
  "floor_jungle_planks": "floor_jungle_planks.png",
  "floor_light_blue_stained_glass": "floor_light_blue_stained_glass.png",
  "floor_light_gray_stained_glass": "floor_light_gray_stained_glass.png",
  "floor_magenta_stained_glass": "floor_magenta_stained_glass.png",
  "floor_oak_planks": "floor_oak_planks.png",
  "floor_pink_stained_glass": "floor_pink_stained_glass.png",
  "floor_red_stained_glass": "floor_red_stained_glass.png",
  "floor_sol_carreaux_bleu": "floor_sol_carreaux_bleu.png",
  "floor_sol_checkerboard": "floor_sol_checkerboard.png",
  "floor_spruce_planks": "floor_spruce_planks.png",
  "floor_stone": "floor_stone.png",
  "floor_stone_bricks": "floor_stone_bricks.png",
  "floor_white_stained_glass": "floor_white_stained_glass.png",
  "floor_wood": "floor_wood.png",
  "floor_yellow_stained_glass": "floor_yellow_stained_glass.png",
  "flower_pot": "flower_pot.png",
  "fridge": "fridge.png",
  "furnace_close": "furnace_close.png",
  "furnace_open": "furnace_open.png",
  "green_flag": "green_flag.png",
  "green_princess_bed": "green_princess_bed.png",
  "harrow": "harrow.png",
  "heart_flag": "heart_flag.png",
  "industrial_barrel": "industrial_barrel.png",
  "iron_helmet_rack": "iron_helmet_rack.png",
  "katana_stand": "katana_stand.png",
  "kitchen_counter": "kitchen_counter.png",
  "lampe": "lampe.png",
  "lavabo": "lavabo.png",
  "leather_sofa": "leather_sofa.png",
  "lit_double_droite": "lit_double_droite.png",
  "lit_double_face": "lit_double_face.png",
  "lit_double_gauche": "lit_double_gauche.png",
  "lit_simple": "lit_simple.png",
  "lit_simple_droite": "lit_simple_droite.png",
  "lit_simple_gauche": "lit_simple_gauche.png",
  "log": "log.png",
  "loot_chest": "loot_chest.png",
  "loot_chest2": "loot_chest2.png",
  "mana_pool": "mana_pool.png",
  "medieval_door": "medieval_door.png",
  "meeting_table": "meeting_table.png",
  "microscope": "microscope.png",
  "mirroir": "mirroir.png",
  "mystery_box": "mystery_box.png",
  "office_chair": "office_chair.png",
  "oil_barrel": "oil_barrel.png",
  "old_fashioned_clock": "old_fashioned_clock.png",
  "old_fashioned_clock2": "old_fashioned_clock2.png",
  "old_fashioned_tv": "old_fashioned_tv.png",
  "orange_flag": "orange_flag.png",
  "pills": "pills.png",
  "pirate_flag": "pirate_flag.png",
  "plant_arch": "plant_arch.png",
  "portable_camera": "portable_camera.png",
  "portable_video_camera": "portable_video_camera.png",
  "presentation_screen": "presentation_screen.png",
  "purple_dog_basket": "purple_dog_basket.png",
  "purple_flag": "purple_flag.png",
  "purple_sofa": "purple_sofa.png",
  "radioactive_barrels": "radioactive_barrels.png",
  "ray_gun": "ray_gun.png",
  "red_flag": "red_flag.png",
  "round_table": "round_table.png",
  "royal_chair": "royal_chair.png",
  "rug_blue": "rug_blue.png",
  "rug_green": "rug_green.png",
  "rug_red": "rug_red.png",
  "rug_white": "rug_white.png",
  "sci_fi_console": "sci_fi_console.png",
  "sci_fi_desk": "sci_fi_desk.png",
  "server_rack": "server_rack.png",
  "shelf1": "shelf1.png",
  "shelf2": "shelf2.png",
  "shelf3": "shelf3.png",
  "shelf4": "shelf4.png",
  "shelf5": "shelf5.png",
  "side_table": "side_table.png",
  "skull_boxing_bag": "skull_boxing_bag.png",
  "skull_chair": "skull_chair.png",
  "skull_tower": "skull_tower.png",
  "smartphone": "smartphone.png",
  "squeleton": "squeleton.png",
  "stool_small": "stool_small.png",
  "syringe": "syringe.png",
  "tapis_blanc": "tapis_blanc.png",
  "tapis_bleu": "tapis_bleu.png",
  "tapis_rouge": "tapis_rouge.png",
  "tapis_vert": "tapis_vert.png",
  "training_dummy": "training_dummy.png",
  "tv": "tv.png",
  "tv_console": "tv_console.png",
  "uzi_gun": "uzi_gun.png",
  "vital_monitor": "vital_monitor.png",
  "vital_signs_monitor": "vital_signs_monitor.png",
  "wall_acacia_planks": "wall_acacia_planks.png",
  "wall_bamboo_planks": "wall_bamboo_planks.png",
  "wall_birch_planks": "wall_birch_planks.png",
  "wall_brick": "wall_brick.png",
  "wall_bricks": "wall_bricks.png",
  "wall_cherry_planks": "wall_cherry_planks.png",
  "wall_clock": "wall_clock.png",
  "wall_cobblestone": "wall_cobblestone.png",
  "wall_dark_oak_planks": "wall_dark_oak_planks.png",
  "wall_deepslate_bricks": "wall_deepslate_bricks.png",
  "wall_deepslate_tiles": "wall_deepslate_tiles.png",
  "wall_glass": "wall_glass.png",
  "wall_green_stained_glass": "wall_green_stained_glass.png",
  "wall_jungle_planks": "wall_jungle_planks.png",
  "wall_light_blue_stained_glass": "wall_light_blue_stained_glass.png",
  "wall_light_gray_stained_glass": "wall_light_gray_stained_glass.png",
  "wall_magenta_stained_glass": "wall_magenta_stained_glass.png",
  "wall_oak_planks": "wall_oak_planks.png",
  "wall_pink_stained_glass": "wall_pink_stained_glass.png",
  "wall_red_stained_glass": "wall_red_stained_glass.png",
  "wall_sol_carreaux_bleu": "wall_sol_carreaux_bleu.png",
  "wall_sol_checkerboard": "wall_sol_checkerboard.png",
  "wall_spruce_planks": "wall_spruce_planks.png",
  "wall_stone": "wall_stone.png",
  "wall_stone_bricks": "wall_stone_bricks.png",
  "wall_tan": "wall_tan.png",
  "wall_white_stained_glass": "wall_white_stained_glass.png",
  "wall_yellow_stained_glass": "wall_yellow_stained_glass.png",
  "wardrobe_brown": "wardrobe_brown.png",
  "water_feature": "water_feature.png",
  "wc": "wc.png",
  "white_blank_flag": "white_blank_flag.png",
  "white_chair": "white_chair.png",
  "window_blue": "window_blue.png",
  "wooden_table": "wooden_table.png",
  "wooden_table2": "wooden_table2.png",
  "working_table": "working_table.png",
  "writing_desk": "writing_desk.png",
} as const;

export type AssetId = keyof typeof OFFICE_ASSETS;
export type ImageMap = Record<AssetId, HTMLImageElement>;

export const BUILD_ASSET_IDS = [
  "floor_acacia_planks",
  "floor_bamboo_planks",
  "floor_birch_planks",
  "floor_blue",
  "floor_bricks",
  "floor_checker",
  "floor_cherry_planks",
  "floor_cobblestone",
  "floor_dark_oak_planks",
  "floor_deepslate_bricks",
  "floor_deepslate_tiles",
  "floor_glass",
  "floor_green_stained_glass",
  "floor_jungle_planks",
  "floor_light_blue_stained_glass",
  "floor_light_gray_stained_glass",
  "floor_magenta_stained_glass",
  "floor_oak_planks",
  "floor_pink_stained_glass",
  "floor_red_stained_glass",
  "floor_sol_carreaux_bleu",
  "floor_sol_checkerboard",
  "floor_spruce_planks",
  "floor_stone",
  "floor_stone_bricks",
  "floor_white_stained_glass",
  "floor_wood",
  "floor_yellow_stained_glass",
  "wall_acacia_planks",
  "wall_bamboo_planks",
  "wall_birch_planks",
  "wall_brick",
  "wall_bricks",
  "wall_cherry_planks",
  "wall_cobblestone",
  "wall_dark_oak_planks",
  "wall_deepslate_bricks",
  "wall_deepslate_tiles",
  "wall_glass",
  "wall_green_stained_glass",
  "wall_jungle_planks",
  "wall_light_blue_stained_glass",
  "wall_light_gray_stained_glass",
  "wall_magenta_stained_glass",
  "wall_oak_planks",
  "wall_pink_stained_glass",
  "wall_red_stained_glass",
  "wall_sol_carreaux_bleu",
  "wall_sol_checkerboard",
  "wall_spruce_planks",
  "wall_stone",
  "wall_stone_bricks",
  "wall_tan",
  "wall_white_stained_glass",
  "wall_yellow_stained_glass",
] satisfies AssetId[];

export const FLOOR_LAYER_ASSET_IDS = [
  "mana_pool",
  "rug_blue",
  "rug_green",
  "rug_red",
  "rug_white",
  "tapis_blanc",
  "tapis_bleu",
  "tapis_rouge",
  "tapis_vert",
  "water_feature",
] satisfies AssetId[];

export async function loadOfficeImages(): Promise<ImageMap> {
  const entries = Object.entries(OFFICE_ASSETS) as [AssetId, string][];
  const loaded = await Promise.all(
    entries.map(([id, file]) => {
      return new Promise<[AssetId, HTMLImageElement]>((resolve, reject) => {
        const image = new Image();
        image.onload = () => resolve([id, image]);
        image.onerror = () => reject(new Error(`Unable to load ${file}`));
        image.src = `${ASSET_BASE}/${file}`;
      });
    })
  );

  return Object.fromEntries(loaded) as ImageMap;
}
