export const ASSET_BASE = "/assets/office";
export const ASSET_VERSION = "f4afdf12bbf0";

export const OFFICE_ASSETS = {
  "amethyst": "amethyst.png",
  "anvil": "anvil.png",
  "aquarium_sofa": "aquarium_sofa.png",
  "armchair_green": "armchair_green.png",
  "barrel": "barrel.png",
  "battery": "battery.png",
  "battery2": "battery2.png",
  "battery3": "battery3.png",
  "bed1": "bed1.png",
  "bibliotheque": "bibliotheque.png",
  "biohazard_box": "biohazard_box.png",
  "black_flag": "black_flag.png",
  "black_medieval_chair": "black_medieval_chair.png",
  "blue_medieval_chair": "blue_medieval_chair.png",
  "bonxing_bag3": "bonxing_bag3.png",
  "bookcase_brown": "bookcase_brown.png",
  "bookcase_small": "bookcase_small.png",
  "bookshelf1": "bookshelf1.png",
  "bookshelf2": "bookshelf2.png",
  "bookshelf4": "bookshelf4.png",
  "bookshelf5": "bookshelf5.png",
  "bookshelf6": "bookshelf6.png",
  "bookshelf_3": "bookshelf_3.png",
  "bookshelf_lounge": "bookshelf_lounge.png",
  "boxing_bag": "boxing_bag.png",
  "boxing_bag2": "boxing_bag2.png",
  "bureau": "bureau.png",
  "cabine_douche": "cabine_douche.png",
  "cabinet_big": "cabinet_big.png",
  "cards": "cards.png",
  "chair_blue": "chair_blue.png",
  "chair_red": "chair_red.png",
  "chair_wood": "chair_wood.png",
  "chemistry_bottle": "chemistry_bottle.png",
  "chemistry_flasks": "chemistry_flasks.png",
  "chest_of_drawers": "chest_of_drawers.png",
  "coffee_machine": "coffee_machine.png",
  "coffee_table": "coffee_table.png",
  "commode": "commode.png",
  "commode_arriere": "commode_arriere.png",
  "commode_face": "commode_face.png",
  "conference_table": "conference_table.png",
  "cooker_hood": "cooker_hood.png",
  "cooking_hood2": "cooking_hood2.png",
  "cooking_robot": "cooking_robot.png",
  "couch_red_small": "couch_red_small.png",
  "cozy_sofa": "cozy_sofa.png",
  "dark_pruple_sofa": "dark_pruple_sofa.png",
  "death_totem": "death_totem.png",
  "desk_simple": "desk_simple.png",
  "diy_table": "diy_table.png",
  "diy_table2": "diy_table2.png",
  "dracula_chair": "dracula_chair.png",
  "dresser_brown": "dresser_brown.png",
  "fauteuil_rouge": "fauteuil_rouge.png",
  "fenetre": "fenetre.png",
  "fighting_dummy2": "fighting_dummy2.png",
  "fighting_dummy3": "fighting_dummy3.png",
  "fighting_dummy4": "fighting_dummy4.png",
  "fireplace": "fireplace.png",
  "flag_holder": "flag_holder.png",
  "floor_acacia_planks": "floor_acacia_planks.png",
  "floor_bamboo_planks": "floor_bamboo_planks.png",
  "floor_birch_planks": "floor_birch_planks.png",
  "floor_blue": "floor_blue.png",
  "floor_bricks": "floor_bricks.png",
  "floor_checker": "floor_checker.png",
  "floor_cherry_planks": "floor_cherry_planks.png",
  "floor_cobblestone": "floor_cobblestone.png",
  "floor_dark_oak_planks": "floor_dark_oak_planks.png",
  "floor_deepslate_bricks": "floor_deepslate_bricks.png",
  "floor_deepslate_tiles": "floor_deepslate_tiles.png",
  "floor_glass": "floor_glass.png",
  "floor_green_stained_glass": "floor_green_stained_glass.png",
  "floor_jungle_planks": "floor_jungle_planks.png",
  "floor_light_blue_stained_glass": "floor_light_blue_stained_glass.png",
  "floor_light_gray_stained_glass": "floor_light_gray_stained_glass.png",
  "floor_magenta_stained_glass": "floor_magenta_stained_glass.png",
  "floor_oak_planks": "floor_oak_planks.png",
  "floor_pink_stained_glass": "floor_pink_stained_glass.png",
  "floor_red_stained_glass": "floor_red_stained_glass.png",
  "floor_sol_carreaux_bleu": "floor_sol_carreaux_bleu.png",
  "floor_sol_checkerboard": "floor_sol_checkerboard.png",
  "floor_spruce_planks": "floor_spruce_planks.png",
  "floor_stone": "floor_stone.png",
  "floor_stone_bricks": "floor_stone_bricks.png",
  "floor_white_stained_glass": "floor_white_stained_glass.png",
  "floor_wood": "floor_wood.png",
  "floor_yellow_stained_glass": "floor_yellow_stained_glass.png",
  "flower_pot": "flower_pot.png",
  "fridge": "fridge.png",
  "furnace_close": "furnace_close.png",
  "furnace_open": "furnace_open.png",
  "green_flag": "green_flag.png",
  "green_princess_bed": "green_princess_bed.png",
  "harrow": "harrow.png",
  "heart_flag": "heart_flag.png",
  "industrial_barrel": "industrial_barrel.png",
  "iron_helmet_rack": "iron_helmet_rack.png",
  "katana_stand": "katana_stand.png",
  "kitchen_counter": "kitchen_counter.png",
  "lampe": "lampe.png",
  "lavabo": "lavabo.png",
  "leather_sofa": "leather_sofa.png",
  "lit_double_droite": "lit_double_droite.png",
  "lit_double_face": "lit_double_face.png",
  "lit_double_gauche": "lit_double_gauche.png",
  "lit_simple": "lit_simple.png",
  "lit_simple_droite": "lit_simple_droite.png",
  "lit_simple_gauche": "lit_simple_gauche.png",
  "log": "log.png",
  "loot_chest": "loot_chest.png",
  "loot_chest2": "loot_chest2.png",
  "mana_pool": "mana_pool.png",
  "medieval_door": "medieval_door.png",
  "meeting_table": "meeting_table.png",
  "microscope": "microscope.png",
  "mirroir": "mirroir.png",
  "mystery_box": "mystery_box.png",
  "office_chair": "office_chair.png",
  "oil_barrel": "oil_barrel.png",
  "old_fashioned_clock": "old_fashioned_clock.png",
  "old_fashioned_clock2": "old_fashioned_clock2.png",
  "old_fashioned_tv": "old_fashioned_tv.png",
  "orange_flag": "orange_flag.png",
  "pills": "pills.png",
  "pirate_flag": "pirate_flag.png",
  "plant_arch": "plant_arch.png",
  "portable_camera": "portable_camera.png",
  "portable_video_camera": "portable_video_camera.png",
  "presentation_screen": "presentation_screen.png",
  "purple_dog_basket": "purple_dog_basket.png",
  "purple_flag": "purple_flag.png",
  "purple_sofa": "purple_sofa.png",
  "radioactive_barrels": "radioactive_barrels.png",
  "ray_gun": "ray_gun.png",
  "red_flag": "red_flag.png",
  "round_table": "round_table.png",
  "royal_chair": "royal_chair.png",
  "rug_blue": "rug_blue.png",
  "rug_green": "rug_green.png",
  "rug_red": "rug_red.png",
  "rug_white": "rug_white.png",
  "sci_fi_console": "sci_fi_console.png",
  "sci_fi_desk": "sci_fi_desk.png",
  "server_rack": "server_rack.png",
  "shelf1": "shelf1.png",
  "shelf2": "shelf2.png",
  "shelf3": "shelf3.png",
  "shelf4": "shelf4.png",
  "shelf5": "shelf5.png",
  "side_table": "side_table.png",
  "skull_boxing_bag": "skull_boxing_bag.png",
  "skull_chair": "skull_chair.png",
  "skull_tower": "skull_tower.png",
  "smartphone": "smartphone.png",
  "squeleton": "squeleton.png",
  "stool_small": "stool_small.png",
  "syringe": "syringe.png",
  "tapis_blanc": "tapis_blanc.png",
  "tapis_bleu": "tapis_bleu.png",
  "tapis_rouge": "tapis_rouge.png",
  "tapis_vert": "tapis_vert.png",
  "training_dummy": "training_dummy.png",
  "tv": "tv.png",
  "tv_console": "tv_console.png",
  "uzi_gun": "uzi_gun.png",
  "vital_monitor": "vital_monitor.png",
  "vital_signs_monitor": "vital_signs_monitor.png",
  "wall_acacia_planks": "wall_acacia_planks.png",
  "wall_bamboo_planks": "wall_bamboo_planks.png",
  "wall_birch_planks": "wall_birch_planks.png",
  "wall_brick": "wall_brick.png",
  "wall_bricks": "wall_bricks.png",
  "wall_cherry_planks": "wall_cherry_planks.png",
  "wall_clock": "wall_clock.png",
  "wall_cobblestone": "wall_cobblestone.png",
  "wall_dark_oak_planks": "wall_dark_oak_planks.png",
  "wall_deepslate_bricks": "wall_deepslate_bricks.png",
  "wall_deepslate_tiles": "wall_deepslate_tiles.png",
  "wall_glass": "wall_glass.png",
  "wall_green_stained_glass": "wall_green_stained_glass.png",
  "wall_jungle_planks": "wall_jungle_planks.png",
  "wall_light_blue_stained_glass": "wall_light_blue_stained_glass.png",
  "wall_light_gray_stained_glass": "wall_light_gray_stained_glass.png",
  "wall_magenta_stained_glass": "wall_magenta_stained_glass.png",
  "wall_oak_planks": "wall_oak_planks.png",
  "wall_pink_stained_glass": "wall_pink_stained_glass.png",
  "wall_red_stained_glass": "wall_red_stained_glass.png",
  "wall_sol_carreaux_bleu": "wall_sol_carreaux_bleu.png",
  "wall_sol_checkerboard": "wall_sol_checkerboard.png",
  "wall_spruce_planks": "wall_spruce_planks.png",
  "wall_stone": "wall_stone.png",
  "wall_stone_bricks": "wall_stone_bricks.png",
  "wall_tan": "wall_tan.png",
  "wall_white_stained_glass": "wall_white_stained_glass.png",
  "wall_yellow_stained_glass": "wall_yellow_stained_glass.png",
  "wardrobe_brown": "wardrobe_brown.png",
  "water_feature": "water_feature.png",
  "wc": "wc.png",
  "white_blank_flag": "white_blank_flag.png",
  "white_chair": "white_chair.png",
  "window_blue": "window_blue.png",
  "wooden_table": "wooden_table.png",
  "wooden_table2": "wooden_table2.png",
  "working_table": "working_table.png",
  "writing_desk": "writing_desk.png",
} as const;

export type AssetId = keyof typeof OFFICE_ASSETS;
export type ImageMap = Record<AssetId, HTMLImageElement>;

export interface OfficeAssetMeta {
  category: string;
  group: string;
  label: string;
  source: string;
  width: number;
  height: number;
}

export const OFFICE_ASSET_META = {
  "amethyst": {"category": "decor", "group": "universal", "label": "Amethyst", "source": "assets/props/universal/amethyst.png", "width": 24, "height": 24},
  "anvil": {"category": "decor", "group": "universal", "label": "Anvil", "source": "assets/props/universal/anvil.png", "width": 24, "height": 24},
  "aquarium_sofa": {"category": "furniture", "group": "living_room", "label": "Aquarium Sofa", "source": "assets/props/living_room/aquarium_sofa.png", "width": 61, "height": 32},
  "armchair_green": {"category": "furniture", "group": "living_room", "label": "Armchair Green", "source": "assets/props/living_room/royal_chair.png", "width": 24, "height": 24},
  "barrel": {"category": "furniture", "group": "kitchen", "label": "Barrel", "source": "assets/props/kitchen/barrel.png", "width": 25, "height": 30},
  "battery": {"category": "decor", "group": "universal", "label": "Battery", "source": "assets/props/universal/battery.png", "width": 18, "height": 26},
  "battery2": {"category": "decor", "group": "universal", "label": "Battery2", "source": "assets/props/universal/battery2.png", "width": 15, "height": 25},
  "battery3": {"category": "decor", "group": "universal", "label": "Battery3", "source": "assets/props/universal/battery3.png", "width": 20, "height": 30},
  "bed1": {"category": "furniture", "group": "bedroom", "label": "Bed1", "source": "assets/props/bedroom/bed1.png", "width": 40, "height": 21},
  "bibliotheque": {"category": "furniture", "group": "living_room", "label": "Bibliotheque", "source": "assets/props/living_room/bibliotheque.png", "width": 26, "height": 56},
  "biohazard_box": {"category": "decor", "group": "universal", "label": "Biohazard Box", "source": "assets/props/universal/biohazard_box.png", "width": 27, "height": 25},
  "black_flag": {"category": "decor", "group": "universal", "label": "Black Flag", "source": "assets/props/universal/black_flag.png", "width": 24, "height": 24},
  "black_medieval_chair": {"category": "furniture", "group": "living_room", "label": "Black Medieval Chair", "source": "assets/props/living_room/black_medieval_chair.png", "width": 24, "height": 24},
  "blue_medieval_chair": {"category": "furniture", "group": "living_room", "label": "Blue Medieval Chair", "source": "assets/props/living_room/blue_medieval_chair.png", "width": 24, "height": 24},
  "bonxing_bag3": {"category": "decor", "group": "universal", "label": "Bonxing Bag3", "source": "assets/props/universal/bonxing_bag3.png", "width": 24, "height": 24},
  "bookcase_brown": {"category": "furniture", "group": "living_room", "label": "Bookcase Brown", "source": "assets/props/living_room/bibliotheque.png", "width": 26, "height": 56},
  "bookcase_small": {"category": "furniture", "group": "living_room", "label": "Bookcase Small", "source": "assets/props/living_room/bookshelf4.png", "width": 24, "height": 24},
  "bookshelf1": {"category": "furniture", "group": "living_room", "label": "Bookshelf1", "source": "assets/props/living_room/bookshelf1.png", "width": 24, "height": 24},
  "bookshelf2": {"category": "furniture", "group": "living_room", "label": "Bookshelf2", "source": "assets/props/living_room/bookshelf2.png", "width": 24, "height": 24},
  "bookshelf4": {"category": "furniture", "group": "living_room", "label": "Bookshelf4", "source": "assets/props/living_room/bookshelf4.png", "width": 24, "height": 24},
  "bookshelf5": {"category": "decor", "group": "universal", "label": "Bookshelf5", "source": "assets/props/universal/bookshelf5.png", "width": 24, "height": 24},
  "bookshelf6": {"category": "decor", "group": "universal", "label": "Bookshelf6", "source": "assets/props/universal/bookshelf6.png", "width": 24, "height": 24},
  "bookshelf_3": {"category": "furniture", "group": "living_room", "label": "Bookshelf 3", "source": "assets/props/living_room/bookshelf_3.png", "width": 24, "height": 24},
  "bookshelf_lounge": {"category": "furniture", "group": "universal", "label": "Bookshelf Lounge", "source": "assets/props/universal/bookshelf6.png", "width": 24, "height": 24},
  "boxing_bag": {"category": "decor", "group": "universal", "label": "Boxing Bag", "source": "assets/props/universal/boxing_bag.png", "width": 24, "height": 24},
  "boxing_bag2": {"category": "decor", "group": "universal", "label": "Boxing Bag2", "source": "assets/props/universal/boxing_bag2.png", "width": 24, "height": 24},
  "bureau": {"category": "furniture", "group": "desk", "label": "Bureau", "source": "assets/props/desk/bureau.png", "width": 53, "height": 37},
  "cabine_douche": {"category": "furniture", "group": "bathroom", "label": "Cabine Douche", "source": "assets/props/bathroom/cabine_douche.png", "width": 25, "height": 63},
  "cabinet_big": {"category": "furniture", "group": "living_room", "label": "Cabinet Big", "source": "assets/props/living_room/commode_face.png", "width": 26, "height": 26},
  "cards": {"category": "decor", "group": "universal", "label": "Cards", "source": "assets/props/universal/cards.png", "width": 33, "height": 26},
  "chair_blue": {"category": "furniture", "group": "living_room", "label": "Chair Blue", "source": "assets/props/living_room/blue_medieval_chair.png", "width": 24, "height": 24},
  "chair_red": {"category": "furniture", "group": "living_room", "label": "Chair Red", "source": "assets/props/living_room/fauteuil_rouge.png", "width": 23, "height": 23},
  "chair_wood": {"category": "furniture", "group": "living_room", "label": "Chair Wood", "source": "assets/props/living_room/white_chair.png", "width": 18, "height": 22},
  "chemistry_bottle": {"category": "decor", "group": "universal", "label": "Chemistry Bottle", "source": "assets/props/universal/chemistry_bottle.png", "width": 17, "height": 27},
  "chemistry_flasks": {"category": "decor", "group": "universal", "label": "Chemistry Flasks", "source": "assets/props/universal/chemistry_flasks.png", "width": 26, "height": 20},
  "chest_of_drawers": {"category": "furniture", "group": "living_room", "label": "Chest Of Drawers", "source": "assets/props/living_room/chest_of_drawers.png", "width": 46, "height": 22},
  "coffee_machine": {"category": "interactive", "group": "kitchen", "label": "Coffee Machine", "source": "assets/props/kitchen/cooking_robot.png", "width": 22, "height": 21},
  "coffee_table": {"category": "furniture", "group": "living_room", "label": "Coffee Table", "source": "assets/props/living_room/wooden_table.png", "width": 24, "height": 24},
  "commode": {"category": "furniture", "group": "living_room", "label": "Commode", "source": "assets/props/living_room/commode.png", "width": 35, "height": 39},
  "commode_arriere": {"category": "furniture", "group": "living_room", "label": "Commode Arriere", "source": "assets/props/living_room/commode_arriére.png", "width": 22, "height": 31},
  "commode_face": {"category": "furniture", "group": "living_room", "label": "Commode Face", "source": "assets/props/living_room/commode_face.png", "width": 26, "height": 26},
  "conference_table": {"category": "furniture", "group": "desk", "label": "Conference Table", "source": "assets/props/desk/bureau.png", "width": 53, "height": 37},
  "cooker_hood": {"category": "furniture", "group": "kitchen", "label": "Cooker Hood", "source": "assets/props/kitchen/cooker_hood.png", "width": 24, "height": 22},
  "cooking_hood2": {"category": "furniture", "group": "kitchen", "label": "Cooking Hood2", "source": "assets/props/kitchen/cooking_hood2.png", "width": 31, "height": 20},
  "cooking_robot": {"category": "furniture", "group": "kitchen", "label": "Cooking Robot", "source": "assets/props/kitchen/cooking_robot.png", "width": 22, "height": 21},
  "couch_red_small": {"category": "furniture", "group": "living_room", "label": "Couch Red Small", "source": "assets/props/living_room/leather_sofa.png", "width": 46, "height": 23},
  "cozy_sofa": {"category": "furniture", "group": "living_room", "label": "Cozy Sofa", "source": "assets/props/living_room/aquarium_sofa.png", "width": 61, "height": 32},
  "dark_pruple_sofa": {"category": "furniture", "group": "living_room", "label": "Dark Pruple Sofa", "source": "assets/props/living_room/dark_pruple_sofa.png", "width": 50, "height": 21},
  "death_totem": {"category": "decor", "group": "universal", "label": "Death Totem", "source": "assets/props/universal/death_totem.png", "width": 31, "height": 33},
  "desk_simple": {"category": "furniture", "group": "desk", "label": "Desk Simple", "source": "assets/props/desk/bureau.png", "width": 53, "height": 37},
  "diy_table": {"category": "furniture", "group": "living_room", "label": "DIY Table", "source": "assets/props/living_room/DIY_table.png", "width": 24, "height": 24},
  "diy_table2": {"category": "furniture", "group": "living_room", "label": "DIY Table2", "source": "assets/props/living_room/DIY_table2.png", "width": 24, "height": 24},
  "dracula_chair": {"category": "furniture", "group": "living_room", "label": "Dracula Chair", "source": "assets/props/living_room/dracula_chair.png", "width": 24, "height": 24},
  "dresser_brown": {"category": "furniture", "group": "living_room", "label": "Dresser Brown", "source": "assets/props/living_room/chest_of_drawers.png", "width": 46, "height": 22},
  "fauteuil_rouge": {"category": "furniture", "group": "living_room", "label": "Fauteuil Rouge", "source": "assets/props/living_room/fauteuil_rouge.png", "width": 23, "height": 23},
  "fenetre": {"category": "decor", "group": "universal", "label": "Fenetre", "source": "assets/props/universal/fenêtre.png", "width": 27, "height": 28},
  "fighting_dummy2": {"category": "decor", "group": "universal", "label": "Fighting Dummy2", "source": "assets/props/universal/fighting_dummy2.png", "width": 24, "height": 24},
  "fighting_dummy3": {"category": "decor", "group": "universal", "label": "Fighting Dummy3", "source": "assets/props/universal/fighting_dummy3.png", "width": 24, "height": 24},
  "fighting_dummy4": {"category": "decor", "group": "universal", "label": "Fighting Dummy4", "source": "assets/props/universal/fighting_dummy4.png", "width": 24, "height": 24},
  "fireplace": {"category": "furniture", "group": "living_room", "label": "Fireplace", "source": "assets/props/living_room/furnace_close.png", "width": 24, "height": 24},
  "flag_holder": {"category": "decor", "group": "universal", "label": "Flag Holder", "source": "assets/props/universal/flag_holder.png", "width": 24, "height": 24},
  "floor_acacia_planks": {"category": "floor", "group": "floor", "label": "Floor Acacia Planks", "source": "assets/building/acacia_planks.png", "width": 16, "height": 16},
  "floor_bamboo_planks": {"category": "floor", "group": "floor", "label": "Floor Bamboo Planks", "source": "assets/building/bamboo_planks.png", "width": 16, "height": 16},
  "floor_birch_planks": {"category": "floor", "group": "floor", "label": "Floor Birch Planks", "source": "assets/building/birch_planks.png", "width": 16, "height": 16},
  "floor_blue": {"category": "floor", "group": "floor", "label": "Floor Blue", "source": "assets/building/sol_carreaux_bleu.png", "width": 16, "height": 16},
  "floor_bricks": {"category": "floor", "group": "floor", "label": "Floor Bricks", "source": "assets/building/bricks.png", "width": 16, "height": 16},
  "floor_checker": {"category": "floor", "group": "floor", "label": "Floor Checker", "source": "assets/building/sol_checkerboard.png", "width": 16, "height": 16},
  "floor_cherry_planks": {"category": "floor", "group": "floor", "label": "Floor Cherry Planks", "source": "assets/building/cherry_planks.png", "width": 16, "height": 16},
  "floor_cobblestone": {"category": "floor", "group": "floor", "label": "Floor Cobblestone", "source": "assets/building/cobblestone.png", "width": 16, "height": 16},
  "floor_dark_oak_planks": {"category": "floor", "group": "floor", "label": "Floor Dark Oak Planks", "source": "assets/building/dark_oak_planks.png", "width": 16, "height": 16},
  "floor_deepslate_bricks": {"category": "floor", "group": "floor", "label": "Floor Deepslate Bricks", "source": "assets/building/deepslate_bricks.png", "width": 16, "height": 16},
  "floor_deepslate_tiles": {"category": "floor", "group": "floor", "label": "Floor Deepslate Tiles", "source": "assets/building/deepslate_tiles.png", "width": 16, "height": 16},
  "floor_glass": {"category": "floor", "group": "floor", "label": "Floor Glass", "source": "assets/building/glass.png", "width": 16, "height": 16},
  "floor_green_stained_glass": {"category": "floor", "group": "floor", "label": "Floor Green Stained Glass", "source": "assets/building/green_stained_glass.png", "width": 16, "height": 16},
  "floor_jungle_planks": {"category": "floor", "group": "floor", "label": "Floor Jungle Planks", "source": "assets/building/jungle_planks.png", "width": 16, "height": 16},
  "floor_light_blue_stained_glass": {"category": "floor", "group": "floor", "label": "Floor Light Blue Stained Glass", "source": "assets/building/light_blue_stained_glass.png", "width": 16, "height": 16},
  "floor_light_gray_stained_glass": {"category": "floor", "group": "floor", "label": "Floor Light Gray Stained Glass", "source": "assets/building/light_gray_stained_glass.png", "width": 16, "height": 16},
  "floor_magenta_stained_glass": {"category": "floor", "group": "floor", "label": "Floor Magenta Stained Glass", "source": "assets/building/magenta_stained_glass.png", "width": 16, "height": 16},
  "floor_oak_planks": {"category": "floor", "group": "floor", "label": "Floor Oak Planks", "source": "assets/building/oak_planks.png", "width": 16, "height": 16},
  "floor_pink_stained_glass": {"category": "floor", "group": "floor", "label": "Floor Pink Stained Glass", "source": "assets/building/pink_stained_glass.png", "width": 16, "height": 16},
  "floor_red_stained_glass": {"category": "floor", "group": "floor", "label": "Floor Red Stained Glass", "source": "assets/building/red_stained_glass.png", "width": 16, "height": 16},
  "floor_sol_carreaux_bleu": {"category": "floor", "group": "floor", "label": "Floor Sol Carreaux Bleu", "source": "assets/building/sol_carreaux_bleu.png", "width": 16, "height": 16},
  "floor_sol_checkerboard": {"category": "floor", "group": "floor", "label": "Floor Sol Checkerboard", "source": "assets/building/sol_checkerboard.png", "width": 16, "height": 16},
  "floor_spruce_planks": {"category": "floor", "group": "floor", "label": "Floor Spruce Planks", "source": "assets/building/spruce_planks.png", "width": 16, "height": 16},
  "floor_stone": {"category": "floor", "group": "floor", "label": "Floor Stone", "source": "assets/building/stone.png", "width": 16, "height": 16},
  "floor_stone_bricks": {"category": "floor", "group": "floor", "label": "Floor Stone Bricks", "source": "assets/building/stone_bricks.png", "width": 16, "height": 16},
  "floor_white_stained_glass": {"category": "floor", "group": "floor", "label": "Floor White Stained Glass", "source": "assets/building/white_stained_glass.png", "width": 16, "height": 16},
  "floor_wood": {"category": "floor", "group": "floor", "label": "Floor Wood", "source": "assets/building/oak_planks.png", "width": 16, "height": 16},
  "floor_yellow_stained_glass": {"category": "floor", "group": "floor", "label": "Floor Yellow Stained Glass", "source": "assets/building/yellow_stained_glass.png", "width": 16, "height": 16},
  "flower_pot": {"category": "furniture", "group": "living_room", "label": "Flower Pot", "source": "assets/props/living_room/flower_pot.png", "width": 24, "height": 24},
  "fridge": {"category": "furniture", "group": "desk", "label": "Fridge", "source": "assets/props/desk/server_rack.png", "width": 22, "height": 28},
  "furnace_close": {"category": "furniture", "group": "living_room", "label": "Furnace Close", "source": "assets/props/living_room/furnace_close.png", "width": 24, "height": 24},
  "furnace_open": {"category": "furniture", "group": "living_room", "label": "Furnace Open", "source": "assets/props/living_room/furnace_open.png", "width": 24, "height": 24},
  "green_flag": {"category": "decor", "group": "universal", "label": "Green Flag", "source": "assets/props/universal/green_flag.png", "width": 24, "height": 24},
  "green_princess_bed": {"category": "furniture", "group": "bedroom", "label": "Green Princess Bed", "source": "assets/props/bedroom/green_princess_bed.png", "width": 38, "height": 28},
  "harrow": {"category": "decor", "group": "universal", "label": "Harrow", "source": "assets/props/universal/harrow.png", "width": 32, "height": 15},
  "heart_flag": {"category": "decor", "group": "universal", "label": "Heart Flag", "source": "assets/props/universal/heart_flag.png", "width": 24, "height": 24},
  "industrial_barrel": {"category": "decor", "group": "universal", "label": "Industrial Barrel", "source": "assets/props/universal/industrial_barrel.png", "width": 16, "height": 24},
  "iron_helmet_rack": {"category": "decor", "group": "universal", "label": "Iron Helmet Rack", "source": "assets/props/universal/iron_helmet_rack.png", "width": 42, "height": 36},
  "katana_stand": {"category": "decor", "group": "universal", "label": "Katana Stand", "source": "assets/props/universal/katana_stand.png", "width": 24, "height": 24},
  "kitchen_counter": {"category": "furniture", "group": "living_room", "label": "Kitchen Counter", "source": "assets/props/living_room/chest_of_drawers.png", "width": 46, "height": 22},
  "lampe": {"category": "decor", "group": "universal", "label": "Lampe", "source": "assets/props/universal/lampe.png", "width": 16, "height": 42},
  "lavabo": {"category": "furniture", "group": "bathroom", "label": "Lavabo", "source": "assets/props/bathroom/lavabo.png", "width": 25, "height": 36},
  "leather_sofa": {"category": "furniture", "group": "living_room", "label": "Leather Sofa", "source": "assets/props/living_room/leather_sofa.png", "width": 46, "height": 23},
  "lit_double_droite": {"category": "furniture", "group": "bedroom", "label": "Lit Double Droite", "source": "assets/props/bedroom/lit_double_droite.png", "width": 45, "height": 54},
  "lit_double_face": {"category": "furniture", "group": "bedroom", "label": "Lit Double Face", "source": "assets/props/bedroom/lit_double_face.png", "width": 43, "height": 47},
  "lit_double_gauche": {"category": "furniture", "group": "bedroom", "label": "Lit Double Gauche", "source": "assets/props/bedroom/lit_double_gauche.png", "width": 45, "height": 54},
  "lit_simple": {"category": "furniture", "group": "bedroom", "label": "Lit Simple", "source": "assets/props/bedroom/lit_simple.png", "width": 22, "height": 47},
  "lit_simple_droite": {"category": "furniture", "group": "bedroom", "label": "Lit Simple Droite", "source": "assets/props/bedroom/lit_simple_droite.png", "width": 44, "height": 36},
  "lit_simple_gauche": {"category": "furniture", "group": "bedroom", "label": "Lit Simple Gauche", "source": "assets/props/bedroom/lit_simple_gauche.png", "width": 44, "height": 36},
  "log": {"category": "decor", "group": "universal", "label": "Log", "source": "assets/props/universal/log.png", "width": 24, "height": 24},
  "loot_chest": {"category": "decor", "group": "universal", "label": "Loot Chest", "source": "assets/props/universal/loot_chest2.png", "width": 31, "height": 20},
  "loot_chest2": {"category": "decor", "group": "universal", "label": "Loot Chest2", "source": "assets/props/universal/loot_chest2.png", "width": 31, "height": 20},
  "mana_pool": {"category": "decor", "group": "universal", "label": "Mana Pool", "source": "assets/props/universal/mana_pool.png", "width": 29, "height": 16},
  "medieval_door": {"category": "decor", "group": "universal", "label": "Medieval Door", "source": "assets/props/universal/medieval_door.png", "width": 23, "height": 31},
  "meeting_table": {"category": "furniture", "group": "living_room", "label": "Meeting Table", "source": "assets/props/living_room/wooden_table2.png", "width": 24, "height": 24},
  "microscope": {"category": "decor", "group": "universal", "label": "Microscope", "source": "assets/props/universal/microscope.png", "width": 22, "height": 30},
  "mirroir": {"category": "furniture", "group": "bathroom", "label": "Mirroir", "source": "assets/props/bathroom/mirroir.png", "width": 27, "height": 32},
  "mystery_box": {"category": "decor", "group": "universal", "label": "Mystery Box", "source": "assets/props/universal/mystery_box.png", "width": 42, "height": 28},
  "office_chair": {"category": "furniture", "group": "living_room", "label": "Office Chair", "source": "assets/props/living_room/white_chair.png", "width": 18, "height": 22},
  "oil_barrel": {"category": "decor", "group": "universal", "label": "Oil Barrel", "source": "assets/props/universal/oil_barrel.png", "width": 20, "height": 30},
  "old_fashioned_clock": {"category": "furniture", "group": "living_room", "label": "Old Fashioned Clock", "source": "assets/props/living_room/old_fashioned_clock.png", "width": 14, "height": 32},
  "old_fashioned_clock2": {"category": "furniture", "group": "living_room", "label": "Old Fashioned Clock2", "source": "assets/props/living_room/old_fashioned_clock2.png", "width": 24, "height": 24},
  "old_fashioned_tv": {"category": "furniture", "group": "living_room", "label": "Old Fashioned TV", "source": "assets/props/living_room/old_fashioned_TV.png", "width": 32, "height": 30},
  "orange_flag": {"category": "decor", "group": "universal", "label": "Orange Flag", "source": "assets/props/universal/orange_flag.png", "width": 24, "height": 24},
  "pills": {"category": "decor", "group": "universal", "label": "Pills", "source": "assets/props/universal/pills.png", "width": 14, "height": 29},
  "pirate_flag": {"category": "decor", "group": "universal", "label": "Pirate Flag", "source": "assets/props/universal/pirate_flag.png", "width": 24, "height": 24},
  "plant_arch": {"category": "decor", "group": "living_room", "label": "Plant Arch", "source": "assets/props/living_room/flower_pot.png", "width": 24, "height": 24},
  "portable_camera": {"category": "decor", "group": "universal", "label": "Portable Camera", "source": "assets/props/universal/portable_video_camera.png", "width": 34, "height": 28},
  "portable_video_camera": {"category": "decor", "group": "universal", "label": "Portable Video Camera", "source": "assets/props/universal/portable_video_camera.png", "width": 34, "height": 28},
  "presentation_screen": {"category": "interactive", "group": "living_room", "label": "Presentation Screen", "source": "assets/props/living_room/old_fashioned_TV.png", "width": 32, "height": 30},
  "purple_dog_basket": {"category": "decor", "group": "universal", "label": "Purple Dog Basket", "source": "assets/props/universal/purple_dog_basket.png", "width": 24, "height": 24},
  "purple_flag": {"category": "decor", "group": "universal", "label": "Purple Flag", "source": "assets/props/universal/purple_flag.png", "width": 24, "height": 24},
  "purple_sofa": {"category": "furniture", "group": "living_room", "label": "Purple Sofa", "source": "assets/props/living_room/purple_sofa.png", "width": 39, "height": 19},
  "radioactive_barrels": {"category": "decor", "group": "universal", "label": "Radioactive Barrels", "source": "assets/props/universal/radioactive_barrels.png", "width": 36, "height": 27},
  "ray_gun": {"category": "decor", "group": "universal", "label": "Ray Gun", "source": "assets/props/universal/ray_gun.png", "width": 40, "height": 25},
  "red_flag": {"category": "decor", "group": "universal", "label": "Red Flag", "source": "assets/props/universal/red_flag.png", "width": 24, "height": 24},
  "round_table": {"category": "furniture", "group": "living_room", "label": "Round Table", "source": "assets/props/living_room/wooden_table2.png", "width": 24, "height": 24},
  "royal_chair": {"category": "furniture", "group": "living_room", "label": "Royal Chair", "source": "assets/props/living_room/royal_chair.png", "width": 24, "height": 24},
  "rug_blue": {"category": "decor", "group": "living_room", "label": "Rug Blue", "source": "assets/props/living_room/tapis_bleu.png", "width": 50, "height": 14},
  "rug_green": {"category": "decor", "group": "living_room", "label": "Rug Green", "source": "assets/props/living_room/tapis_vert.png", "width": 50, "height": 14},
  "rug_red": {"category": "decor", "group": "living_room", "label": "Rug Red", "source": "assets/props/living_room/tapis_rouge.png", "width": 50, "height": 14},
  "rug_white": {"category": "decor", "group": "living_room", "label": "Rug White", "source": "assets/props/living_room/tapis_blanc.png", "width": 50, "height": 14},
  "sci_fi_console": {"category": "furniture", "group": "desk", "label": "Sci-fi Console", "source": "assets/props/desk/sci-fi_console.png", "width": 40, "height": 32},
  "sci_fi_desk": {"category": "furniture", "group": "desk", "label": "Sci-fi Desk", "source": "assets/props/desk/sci-fi_desk.png", "width": 38, "height": 23},
  "server_rack": {"category": "furniture", "group": "desk", "label": "Server Rack", "source": "assets/props/desk/server_rack.png", "width": 22, "height": 28},
  "shelf1": {"category": "decor", "group": "universal", "label": "Shelf1", "source": "assets/props/universal/shelf1.png", "width": 47, "height": 10},
  "shelf2": {"category": "furniture", "group": "living_room", "label": "Shelf2", "source": "assets/props/living_room/shelf2.png", "width": 25, "height": 26},
  "shelf3": {"category": "furniture", "group": "living_room", "label": "Shelf3", "source": "assets/props/living_room/shelf3.png", "width": 39, "height": 15},
  "shelf4": {"category": "furniture", "group": "living_room", "label": "Shelf4", "source": "assets/props/living_room/shelf4.png", "width": 24, "height": 24},
  "shelf5": {"category": "furniture", "group": "living_room", "label": "Shelf5", "source": "assets/props/living_room/shelf5.png", "width": 24, "height": 24},
  "side_table": {"category": "furniture", "group": "living_room", "label": "Side Table", "source": "assets/props/living_room/DIY_table.png", "width": 24, "height": 24},
  "skull_boxing_bag": {"category": "decor", "group": "universal", "label": "Skull Boxing Bag", "source": "assets/props/universal/skull_boxing_bag.png", "width": 24, "height": 24},
  "skull_chair": {"category": "furniture", "group": "living_room", "label": "Skull Chair", "source": "assets/props/living_room/skull_chair.png", "width": 24, "height": 24},
  "skull_tower": {"category": "decor", "group": "universal", "label": "Skull Tower", "source": "assets/props/universal/skull_tower.png", "width": 24, "height": 24},
  "smartphone": {"category": "decor", "group": "universal", "label": "Smartphone", "source": "assets/props/universal/smartphone.png", "width": 26, "height": 43},
  "squeleton": {"category": "decor", "group": "universal", "label": "Squeleton", "source": "assets/props/universal/squeleton.png", "width": 35, "height": 14},
  "stool_small": {"category": "furniture", "group": "living_room", "label": "Stool Small", "source": "assets/props/living_room/dracula_chair.png", "width": 24, "height": 24},
  "syringe": {"category": "decor", "group": "universal", "label": "Syringe", "source": "assets/props/universal/syringe.png", "width": 27, "height": 27},
  "tapis_blanc": {"category": "furniture", "group": "living_room", "label": "Tapis Blanc", "source": "assets/props/living_room/tapis_blanc.png", "width": 50, "height": 14},
  "tapis_bleu": {"category": "furniture", "group": "living_room", "label": "Tapis Bleu", "source": "assets/props/living_room/tapis_bleu.png", "width": 50, "height": 14},
  "tapis_rouge": {"category": "furniture", "group": "living_room", "label": "Tapis Rouge", "source": "assets/props/living_room/tapis_rouge.png", "width": 50, "height": 14},
  "tapis_vert": {"category": "furniture", "group": "living_room", "label": "Tapis Vert", "source": "assets/props/living_room/tapis_vert.png", "width": 50, "height": 14},
  "training_dummy": {"category": "decor", "group": "universal", "label": "Training Dummy", "source": "assets/props/universal/training_dummy.png", "width": 24, "height": 24},
  "tv": {"category": "furniture", "group": "living_room", "label": "TV", "source": "assets/props/living_room/TV.png", "width": 37, "height": 28},
  "tv_console": {"category": "furniture", "group": "living_room", "label": "TV Console", "source": "assets/props/living_room/TV.png", "width": 37, "height": 28},
  "uzi_gun": {"category": "decor", "group": "universal", "label": "Uzi Gun", "source": "assets/props/universal/uzi_gun.png", "width": 45, "height": 24},
  "vital_monitor": {"category": "decor", "group": "universal", "label": "Vital Monitor", "source": "assets/props/universal/vital_signs_monitor.png", "width": 30, "height": 23},
  "vital_signs_monitor": {"category": "decor", "group": "universal", "label": "Vital Signs Monitor", "source": "assets/props/universal/vital_signs_monitor.png", "width": 30, "height": 23},
  "wall_acacia_planks": {"category": "wall", "group": "wall", "label": "Wall Acacia Planks", "source": "assets/building/acacia_planks.png", "width": 16, "height": 16},
  "wall_bamboo_planks": {"category": "wall", "group": "wall", "label": "Wall Bamboo Planks", "source": "assets/building/bamboo_planks.png", "width": 16, "height": 16},
  "wall_birch_planks": {"category": "wall", "group": "wall", "label": "Wall Birch Planks", "source": "assets/building/birch_planks.png", "width": 16, "height": 16},
  "wall_brick": {"category": "wall", "group": "wall", "label": "Wall Brick", "source": "assets/building/bricks.png", "width": 16, "height": 16},
  "wall_bricks": {"category": "wall", "group": "wall", "label": "Wall Bricks", "source": "assets/building/bricks.png", "width": 16, "height": 16},
  "wall_cherry_planks": {"category": "wall", "group": "wall", "label": "Wall Cherry Planks", "source": "assets/building/cherry_planks.png", "width": 16, "height": 16},
  "wall_clock": {"category": "decor", "group": "living_room", "label": "Wall Clock", "source": "assets/props/living_room/wall_clock.png", "width": 23, "height": 22},
  "wall_cobblestone": {"category": "wall", "group": "wall", "label": "Wall Cobblestone", "source": "assets/building/cobblestone.png", "width": 16, "height": 16},
  "wall_dark_oak_planks": {"category": "wall", "group": "wall", "label": "Wall Dark Oak Planks", "source": "assets/building/dark_oak_planks.png", "width": 16, "height": 16},
  "wall_deepslate_bricks": {"category": "wall", "group": "wall", "label": "Wall Deepslate Bricks", "source": "assets/building/deepslate_bricks.png", "width": 16, "height": 16},
  "wall_deepslate_tiles": {"category": "wall", "group": "wall", "label": "Wall Deepslate Tiles", "source": "assets/building/deepslate_tiles.png", "width": 16, "height": 16},
  "wall_glass": {"category": "wall", "group": "wall", "label": "Wall Glass", "source": "assets/building/glass.png", "width": 16, "height": 16},
  "wall_green_stained_glass": {"category": "wall", "group": "wall", "label": "Wall Green Stained Glass", "source": "assets/building/green_stained_glass.png", "width": 16, "height": 16},
  "wall_jungle_planks": {"category": "wall", "group": "wall", "label": "Wall Jungle Planks", "source": "assets/building/jungle_planks.png", "width": 16, "height": 16},
  "wall_light_blue_stained_glass": {"category": "wall", "group": "wall", "label": "Wall Light Blue Stained Glass", "source": "assets/building/light_blue_stained_glass.png", "width": 16, "height": 16},
  "wall_light_gray_stained_glass": {"category": "wall", "group": "wall", "label": "Wall Light Gray Stained Glass", "source": "assets/building/light_gray_stained_glass.png", "width": 16, "height": 16},
  "wall_magenta_stained_glass": {"category": "wall", "group": "wall", "label": "Wall Magenta Stained Glass", "source": "assets/building/magenta_stained_glass.png", "width": 16, "height": 16},
  "wall_oak_planks": {"category": "wall", "group": "wall", "label": "Wall Oak Planks", "source": "assets/building/oak_planks.png", "width": 16, "height": 16},
  "wall_pink_stained_glass": {"category": "wall", "group": "wall", "label": "Wall Pink Stained Glass", "source": "assets/building/pink_stained_glass.png", "width": 16, "height": 16},
  "wall_red_stained_glass": {"category": "wall", "group": "wall", "label": "Wall Red Stained Glass", "source": "assets/building/red_stained_glass.png", "width": 16, "height": 16},
  "wall_sol_carreaux_bleu": {"category": "wall", "group": "wall", "label": "Wall Sol Carreaux Bleu", "source": "assets/building/sol_carreaux_bleu.png", "width": 16, "height": 16},
  "wall_sol_checkerboard": {"category": "wall", "group": "wall", "label": "Wall Sol Checkerboard", "source": "assets/building/sol_checkerboard.png", "width": 16, "height": 16},
  "wall_spruce_planks": {"category": "wall", "group": "wall", "label": "Wall Spruce Planks", "source": "assets/building/spruce_planks.png", "width": 16, "height": 16},
  "wall_stone": {"category": "wall", "group": "wall", "label": "Wall Stone", "source": "assets/building/stone_bricks.png", "width": 16, "height": 16},
  "wall_stone_bricks": {"category": "wall", "group": "wall", "label": "Wall Stone Bricks", "source": "assets/building/stone_bricks.png", "width": 16, "height": 16},
  "wall_tan": {"category": "wall", "group": "wall", "label": "Wall Tan", "source": "assets/building/acacia_planks.png", "width": 16, "height": 16},
  "wall_white_stained_glass": {"category": "wall", "group": "wall", "label": "Wall White Stained Glass", "source": "assets/building/white_stained_glass.png", "width": 16, "height": 16},
  "wall_yellow_stained_glass": {"category": "wall", "group": "wall", "label": "Wall Yellow Stained Glass", "source": "assets/building/yellow_stained_glass.png", "width": 16, "height": 16},
  "wardrobe_brown": {"category": "furniture", "group": "living_room", "label": "Wardrobe Brown", "source": "assets/props/living_room/commode.png", "width": 35, "height": 39},
  "water_feature": {"category": "decor", "group": "universal", "label": "Water Feature", "source": "assets/props/universal/mana_pool.png", "width": 29, "height": 16},
  "wc": {"category": "furniture", "group": "bathroom", "label": "Wc", "source": "assets/props/bathroom/WC.png", "width": 15, "height": 30},
  "white_blank_flag": {"category": "decor", "group": "universal", "label": "White Blank Flag", "source": "assets/props/universal/white_blank_flag.png", "width": 24, "height": 24},
  "white_chair": {"category": "furniture", "group": "living_room", "label": "White Chair", "source": "assets/props/living_room/white_chair.png", "width": 18, "height": 22},
  "window_blue": {"category": "decor", "group": "universal", "label": "Window Blue", "source": "assets/props/universal/fenêtre.png", "width": 27, "height": 28},
  "wooden_table": {"category": "furniture", "group": "living_room", "label": "Wooden Table", "source": "assets/props/living_room/wooden_table.png", "width": 24, "height": 24},
  "wooden_table2": {"category": "furniture", "group": "living_room", "label": "Wooden Table2", "source": "assets/props/living_room/wooden_table2.png", "width": 24, "height": 24},
  "working_table": {"category": "furniture", "group": "living_room", "label": "Working Table", "source": "assets/props/living_room/working_table.png", "width": 24, "height": 24},
  "writing_desk": {"category": "furniture", "group": "living_room", "label": "Writing Desk", "source": "assets/props/living_room/working_table.png", "width": 24, "height": 24},
} as const satisfies Record<AssetId, OfficeAssetMeta>;

export const BUILD_ASSET_IDS = [
  "floor_acacia_planks",
  "floor_bamboo_planks",
  "floor_birch_planks",
  "floor_blue",
  "floor_bricks",
  "floor_checker",
  "floor_cherry_planks",
  "floor_cobblestone",
  "floor_dark_oak_planks",
  "floor_deepslate_bricks",
  "floor_deepslate_tiles",
  "floor_glass",
  "floor_green_stained_glass",
  "floor_jungle_planks",
  "floor_light_blue_stained_glass",
  "floor_light_gray_stained_glass",
  "floor_magenta_stained_glass",
  "floor_oak_planks",
  "floor_pink_stained_glass",
  "floor_red_stained_glass",
  "floor_sol_carreaux_bleu",
  "floor_sol_checkerboard",
  "floor_spruce_planks",
  "floor_stone",
  "floor_stone_bricks",
  "floor_white_stained_glass",
  "floor_wood",
  "floor_yellow_stained_glass",
  "wall_acacia_planks",
  "wall_bamboo_planks",
  "wall_birch_planks",
  "wall_brick",
  "wall_bricks",
  "wall_cherry_planks",
  "wall_cobblestone",
  "wall_dark_oak_planks",
  "wall_deepslate_bricks",
  "wall_deepslate_tiles",
  "wall_glass",
  "wall_green_stained_glass",
  "wall_jungle_planks",
  "wall_light_blue_stained_glass",
  "wall_light_gray_stained_glass",
  "wall_magenta_stained_glass",
  "wall_oak_planks",
  "wall_pink_stained_glass",
  "wall_red_stained_glass",
  "wall_sol_carreaux_bleu",
  "wall_sol_checkerboard",
  "wall_spruce_planks",
  "wall_stone",
  "wall_stone_bricks",
  "wall_tan",
  "wall_white_stained_glass",
  "wall_yellow_stained_glass",
] satisfies AssetId[];

export const FLOOR_LAYER_ASSET_IDS = [
  "mana_pool",
  "rug_blue",
  "rug_green",
  "rug_red",
  "rug_white",
  "tapis_blanc",
  "tapis_bleu",
  "tapis_rouge",
  "tapis_vert",
  "water_feature",
] satisfies AssetId[];

export function officeAssetUrl(asset: AssetId): string {
  return `${ASSET_BASE}/${OFFICE_ASSETS[asset]}?v=${ASSET_VERSION}`;
}

export async function loadOfficeImages(): Promise<ImageMap> {
  const entries = Object.entries(OFFICE_ASSETS) as [AssetId, string][];
  const loaded = await Promise.all(
    entries.map(([id, file]) => {
      return new Promise<[AssetId, HTMLImageElement]>((resolve, reject) => {
        const image = new Image();
        image.onload = () => resolve([id, image]);
        image.onerror = () => reject(new Error(`Unable to load ${file}`));
        image.src = officeAssetUrl(id);
      });
    })
  );

  return Object.fromEntries(loaded) as ImageMap;
}
